//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@interface JSLogManager : NSObject
{
    _Bool _hasBeenSubmitted;
    long long _countOfDaysHasBeenOpened;
}

+ (id)sharedInstance;
@property(nonatomic) long long countOfDaysHasBeenOpened; // @synthesize countOfDaysHasBeenOpened=_countOfDaysHasBeenOpened;
@property(nonatomic) _Bool hasBeenSubmitted; // @synthesize hasBeenSubmitted=_hasBeenSubmitted;
- (id)init;
- (void)loadLogFromKeychain;

@end

